apertium/lttoolbox

lttoolbox/transducer.h
Use default values to prevent apertium-separable from failing.
Fixes https://github.com/apertium/apertium-separable/issues/4
=> transducer.h: Use default values

lttoolbox/fst_processor.cc, lttoolbox/lt_print.cc, lttoolbox/lt_trim.cc, lttoolbox/pattern_list.cc, lttoolbox/tmx_compiler.cc, lttoolbox/trans_exe.cc, lttoolbox/trans_exe.h, lttoolbox/transducer.cc, lttoolbox/transducer.h
Modify binary read and write functions to prevent
segmentation fault.
Fixes https://github.com/apertium/lttoolbox/issues/27
=> Fix weighted segfault

lttoolbox/xsd/dix.xsd
Attribute "w" for dix entries is declared twice, resulting in a warning when compiling dictionaries. This fixes the issue.
=> Remove duplicate "w" in dix.xsd

.gitignore, lttoolbox/fst_processor.cc, lttoolbox/fst_processor.h, tests/data/gardenpath-mwe.dix, tests/lt_proc/__init__.py, tests/proctest.py
and only print *one* item from blankqueue in printSpace.
This fixes #47. With the input `legge opp<br/>blah`, we'll now have
the regular space in blankqueue and use that before getting to the
<br/>.
Tested on 100.000 lines of html with nno-nob, only good changes found,
and seems to work fine with flushing.
=> Put spaces in blankqueue too, popping if we write a word with spaces

lttoolbox/state.cc, tests/lt_proc/__init__.py
When computing the overall weight of an analysis,
The weight of the final state was ignored.
=> Fix the analysis weight computation bug

lttoolbox/fst_processor.cc
Solves #45
Consider alphanumeric characters to be part of the vocabulary.
=> Fix the out of alphabet token handling in analyses generation

lttoolbox/fst_processor.h
Removed unused decomposition() method from class FSTProcessor
=> Removed: Redundant declaration void FSTProcessor::decomposition()

lttoolbox/att_compiler.cc, lttoolbox/att_compiler.h
=> Properly disjunct multiple FSTs encoded in the same at&t file

python/lttoolbox.i
Loading the dictionary every time would be expensive https://github.com/apertium/apertium-python/issues/52, so load it once during during instantiation
Usage:
```
fst = lttoolbox.FST(dictionary_path)
fst.lt_proc(arg, input_file.name, output_file.name)
```
=> swig wrapper: load dictionary during instantiation

tests/basictest.py, tests/printtest.py, tests/proctest.py
Both printtest and proctest use methods to communicate with the underlying command.
These methods are common and shouldn't be implemented in both modules.
This will also be beneficial for testing further modules such as the lt-print one.
=> Avoid code duplication in testing modules

lttoolbox/transducer.cc
When I added HFST mode to lt-print I mistyped the character escapes because the underscores were interpreted as markdown in the documentation I was reading and I didn't test thoroughly enough to catch it.
=> typo in HFST symbol escapes

lttoolbox/fst_processor.cc
- Removes all trailing secondary tags from the input before giving it to FST matching.
- For input without secondary tags it works as earlier with no regression.
- All escaped characters are ignored inside secondary tags, as well as unescaped special characters ($,#,etc.) This applies for the tag prefix as well
This is needed for generation.
Input:
```
^The<det><def><pl><sf:Los>$ ^dog<n><pl><sf:perros>$ ^of<pr><sf:del>$ ^the<det><def><sg><sf:del>$ ^boy<n><sg><sf:chico>$ ^run<vblex><pres><sf:corren>$ ^fast<adj><sint><sf:rápido>$^.<sent><sf:.>$^.<sent><sf:.>$[][
]
```
Earlier Output:
```
#The #dog #of #the #boy #run #fast#.#.[][
]
```
New Output:
```
The dogs of the boy run fast..[][
]
```
=> Ignoring secondary tags during generation

lttoolbox/att_compiler.cc
This should close #9 
Since `lt-proc` can handle initial epsilon transitions correctly, discarding them when compiling ATT files is incorrect and causes problems when converting transducers from HFST.
=> retain initial epsilon transitions when compiling ATT files

lttoolbox/compiler.cc, lttoolbox/compiler.h, lttoolbox/dix.dtd, lttoolbox/dix.rnc, lttoolbox/dix.rng, lttoolbox/expander.cc, lttoolbox/expander.h, lttoolbox/lt-comp.1, lttoolbox/lt-expand.1, lttoolbox/lt_comp.cc, lttoolbox/lt_expand.cc, lttoolbox/xsd/dix.xsd, tests/data/morpheme-boundaries.dix
The compiler and expander now allow `<m/>` inside `<l></l>` sides to represent morpheme boundaries. These are not compiled in, or printed by default, but can be with the `-m` or `--keep-boundaries` option. This closes #89.
=> Add the possibility of defining morpheme boundaries 

lttoolbox/state.cc, lttoolbox/state.h
We needed an alt version of `state.step_override()` to fix_ https://github.com/apertium/apertium-separable/issues/21 and I tried to decrease duplication between the different methods while I was at it.
=> some work on state.step*

lttoolbox/fst_processor.cc, lttoolbox/fst_processor.h, tests/data/wordbound-blank.dix, tests/lt_proc/__init__.py
- Parsing wordbound blanks as normal blanks for analysis, generation, biltrans, postgeneration.
- Also removed unused code for secondary tags.
- Added a test for wordbound blank analysis.
=> Wordbound blanks parsed as normal blanks

lttoolbox/fst_processor.cc, lttoolbox/fst_processor.h, tests/data/postgen.dix, tests/lt_proc/__init__.py
- Wordbound blanks merge when words merge.
- Wordbound blanks apply to all output words when output of postgen rule are more than input words.
- No regression for postgeneration without wordbound blanks.
- Lots of tests added.
Example:
Input:
```
[[t:b:Z9eiLA]]El[[/]] [[t:s:8AjRFw]]perro[[/]] [[t:i:4_tPUA]]~de[[/]] [[t:b:123445]]el[[/]] [[t:i:wSM6RQ]]amigo[[/]][]
```
Output:
```
[[t:b:Z9eiLA]]El[[/]] [[t:s:8AjRFw]]perro[[/]] [[t:i:4_tPUA; t:b:123445]]del[[/]] [[t:i:wSM6RQ]]amigo[[/]][]
```
For more examples see ``PostgenerationWordboundBlankTest`` in ``lttoolbox/tests/lt_proc/__init__.py``.
=> Wordbound blank handling in post generation

lttoolbox/fst_processor.cc
I think this fixes #104 and tests pass, but I'm not totally certain whether any weird things might happen due to, say, stepping by null.
=> be more careful about final LUs in analysis mode (#104)

lttoolbox/fst_processor.cc, lttoolbox/fst_processor.h, tests/data/postgen.dix, tests/lt_proc/__init__.py
There was already support for `[[w:text:foo]]~zzy[[/]] ` but not for
`[[w:text:foo]]xy~zzy[[/]]`
This change should keep the old feature of moving wblank-start after
the post-generated part of `[[w:text:foo]]~zzy[[/]] ` (so if there was
a rule turning `~z` into Z we get `Z[[w:text:foo]]zy[[/]]`), but if the
wake-up-mark `~` is seen later in the wblank, it stays surrounded, so
`[[w:text:foo]]xy~zzy[[/]]` turns into `[[w:text:foo]]xyZzy[[/]]`.
plus tests for https://github.com/apertium/lttoolbox/issues/107 
plus necessary changes for combineWblanks (can now get called when no
opening wblanks in queue)
(Alternatively I've done a rebase on the icu-branch in case that's going to be merged now-ish https://github.com/apertium/lttoolbox/tree/107-pgenblanks , but I see that branch fails on …
=> Fix #107 – postgenerator fails when ~ in middle of wblanked word

lttoolbox/state.cc
#120
``` shell
$ echo '^ja<ij><copytags>$' | valgrind --leak-check=full ~/PREFIX/lttoolbox/bin/lt-proc -b ../apertium-nno-nob/nob-nno.autobil.bin
==776548== Memcheck, a memory error detector
==776548== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==776548== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==776548== Command: /home/unhammer/PREFIX/lttoolbox/bin/lt-proc -b ../apertium-nno-nob/nob-nno.autobil.bin
==776548==
^ja<ij><copytags>/ja<ij><copytags>$
==776548==
==776548== HEAP SUMMARY:
==776548==     in use at exit: 7,826 bytes in 31 blocks
==776548==   total heap usage: 906,656 allocs, 906,625 frees, 26,955,352 bytes allocated
==776548==
==776548== LEAK SUMMARY:
==776548==    definitely lost: 0 bytes in 0 blocks
==776548==    indirectly lost: 0 …
```
=> Fix #120 leak in State::apply (and variants thereof)

lttoolbox/fst_processor.cc, lttoolbox/fst_processor.h, tests/lt_proc/__init__.py
old code was checking 16-bit code units, thus giving wrong values for
isAlphabetic (which expects a full code point)
Fixes #127
(Related: https://github.com/apertium/apertium/pull/152)
=> Use character iterator when looping codepoints for isAlphabetic

lttoolbox/fst_processor.cc, lttoolbox/fst_processor.h, tests/lt_proc/__init__.py
```
$ echo '𝜊' |lt-proc -p bin  # before
휊
$ echo '𝜊' |lttoolbox/lt-proc -p bin # after
𝜊
```
=> Fix #129 – don't drop UChar32 down to UChar in postgen

lttoolbox/expander.cc
This part of code seems to be duplicating entries when there are direction restrictions in paradigms. Removing it solves the issue without apparent side effects (I have run tests on apertium-cat, apertium-eng and apertium-ron).
I have no deep knowledge of lttoolbox, so someone should probably check I am not breaking anything else. Thanks!
Fixes #125
=> Fix lt-expand duplication

lttoolbox/compiler.cc, lttoolbox/compiler.h, lttoolbox/lt_comp.cc
Basically does
for fst in sections; do minimise fst & done; wait
Testing nob.dix with four sections of about the same size and four
cores gives 25s → 16s wall time.
For now only active when lt-comp -j since memory usage increases (from
410M to 684M RES with the above dix).
(There is no max thread count either, but dix files typically don't
have more than two or three sections, no need to complicate the code
before it becomes an issue.)
=> lt-comp -j: minimise sections in parallel, slice ⅓ off compilation time

lttoolbox/compiler.cc, lttoolbox/compiler.h, lttoolbox/lt-comp.1, lttoolbox/lt_comp.cc
Number is overridable with env var `LT_MAX_SECTION_ENTRIES` 
(e.g. `export LT_MAX_SECTION_ENTRIES=5000`).
Fixes #134
Smaller sections also minimise faster, though after a certain point
the binary starts growing and total time increases again. Benching on
nob.dix where main section is about 260.000 entries, all columns are
with -j (4 cores) except the ones marked -j0:
```
| max entries | cpu secs | wall secs | cpu% | mem kb    | main sections | bin size | -j0 wall | -j0 mem   |
|-------------+----------+-----------+------+-----------+---------------+----------+----------+-----------|
|         500 |    21.62 |     10.87 |  203 |   699_300 |           496 | 4.2M     |    14.91 |   360_524 |
|        1000 |    20.47 |     09.58 |  218 |   658_172 |           248 | 3.7M     |    13.30 | …
```
=> Automatically create new sections after 50k entries when -j

lttoolbox/state.cc, tests/data/sectiondupes.dix, tests/lt_proc/__init__.py
Note: If there are duplicates with different weights, we print the one with the lowest (we still respect max_weight_classes) – is that ever bad?
=> Don't output duplicate strings from state finals, fixes #136

lttoolbox/Makefile.am
Warning during the Debian package build:
https://buildd.debian.org/status/fetch.php?pkg=lttoolbox&arch=amd64&ver=3.6.1-2%2Bb2&stamp=1650723091&raw=0
```
dh_shlibdeps -a
dpkg-shlibdeps: warning: symbol u_strCaseCompare_71 used by debian/liblttoolbox3-3.6-1/usr/lib/x86_64-linux-gnu/liblttoolbox3-3.6.so.1.0.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol u_tolower_71 used by debian/liblttoolbox3-3.6-1/usr/lib/x86_64-linux-gnu/liblttoolbox3-3.6.so.1.0.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol u_isdigit_71 used by debian/liblttoolbox3-3.6-1/usr/lib/x86_64-linux-gnu/liblttoolbox3-3.6.so.1.0.0 found in none of the libraries
dpkg-shlibdeps: warning: symbol u_errorName_71 used by debian/liblttoolbox3-3.6-1/usr/lib/x86_64-linux-gnu/liblttoolbox3-3.6.so.1.0.0 …
```
=> liblttoolbox3 must be linked with libicu

lttoolbox/alphabet.cc, lttoolbox/alphabet.h, lttoolbox/fst_processor.cc, lttoolbox/fst_processor.h, lttoolbox/string_utils.cc, lttoolbox/string_utils.h, tests/basictest.py, tests/data/postgen-overlap.dix, tests/data/postgen-short.dix, tests/lt_proc/__init__.py
Merge postgeneration, intergeneration, and transliteration
* intergen and transliteration now respect wblanks
* postgen now backtracks properly (closes https://github.com/apertium/lttoolbox/issues/123)
* postgen no long requires input to begin with ~ (closes https://github.com/apertium/lttoolbox/issues/42)
* wblank manipulation can no longer produce nested blanks (closes https://github.com/apertium/lttoolbox/issues/145)
* eliminate some dead code
=> Merge Postgen, Intergen, and Transliteration

lttoolbox/acx.rng, lttoolbox/xsd/acx.xsd
token type calls trim() before checking length restriction. After this
change, it's possible to e.g. use acx to treat nbsp as space.
https://relaxng.org/spec-20011203.html
=> validate-acx: datatype of value is string, not token

.gitignore, README, configure.ac, lttoolbox/Makefile.am, lttoolbox/alphabet.cc, lttoolbox/lt-paradigm.1, lttoolbox/lt_paradigm.cc, lttoolbox/transducer.cc, lttoolbox/transducer.h, tests/basictest.py, tests/lt_append/__init__.py, tests/lt_paradigm/__init__.py, tests/lt_print/__init__.py, tests/lt_proc/__init__.py, tests/lt_trim/__init__.py, tests/printtest.py, tests/proctest.py, tests/run_tests.py
This PR adds `lt-paradigm` which is similar to `lt-expand` and `hfst-expand` except that instead of listing all forms in the transducer it only lists those that match an input pattern.
```
$ echo 'sing<vblex><*>' | lttoolbox/lt-paradigm ../apertium-data/apertium-eng/eng.autogen.bin 
sing<vblex><inf>:sing
sing<vblex><pres>:sing
sing<vblex><imp>:sing
sing<vblex><pprs>:singing
sing<vblex><ger>:singing
sing<vblex><subs>:singing
sing<vblex><pres><p3><sg>:sings
sing<vblex><pp>:sung
sing<vblex><past>:sang
```
For each line of the input, `*` is replaced with every letter in the alphabet and `<*>` with every tag and the result is intersected with the fst and the results printed line-by-line.
This is nearly equivalent to `hfst-regexp2fst | hfst-compose -1 - -2 $1 | hfst-expand -c 0` but with …
=> add fst-expander and paradigm generator

lttoolbox/lt-trim.1, lttoolbox/lt_trim.cc
May be given multiple times. Any section matching such a
name (id@type) in the analyser will only be trimmed against sections
with the same name in the bidix. Useful for regex sections, which tend
to have a very different structure from regular entries (few states
with lots of transitions + loops) – leading to slowdown when
intersecting.
This gives a 4x speedup (60s → 15s) on nob→nno:
BEFORE:
```sh
$ \time lttoolbox/lttoolbox/lt-trim apertium-nob/nob.automorf.bin apertium-nno-nob/nob-nno.autobil.bin /tmp/before.bin final@inconditional 26 76
main@standard 168643 350041
regex@standard 403 7475
58.73user 0.97system 1:00.45elapsed 98%CPU (0avgtext+0avgdata 2280784maxresident)k 0inputs+3288outputs (0major+574892minor)pagefaults 0swaps
```
AFTER:
```sh
$ \time lttoolbox/lttoolbox/lt-trim …
```
=> lt-trim: new option --match-section

lttoolbox/fst_processor.cc, lttoolbox/fst_processor.h, lttoolbox/state.cc, lttoolbox/state.h
As suggested in https://github.com/apertium/lttoolbox/issues/167#issuecomment-1276703418 , stop doing the case-insensitive matching when we've got a high number of State sequences.
Currently 65536, quite high but at least within what most modern machines can deal with.
Also, delete FSTProcessor.current_state since confusingly all the processors (except transliteration) make a local State called current_state
```sh
$ cat a.dix 
<?xml version="1.0" encoding="UTF-8"?>
<dictionary>
<alphabet/>
<sdefs>
<sdef n="guess"       c="Guesser"/>
</sdefs>
<pardefs>
<pardef n="a-zA-Z+">
<e><re>[a-zA-Z]+</re></e>
</pardef>
</pardefs>
<section id="regex" type="standard">
<e><par n="a-zA-Z+"/><p><l/><r><s n="guess"/></r></p></e>
</section>
</dictionary>
$ lt-comp lr a.dix a.bin
regex@standard 3 105
$ echo …
```
=> hardcoded sanity-max state size for case-insensitive matching

lttoolbox/acx.h
Needed for int32_t. Fixes build w/ musl but also likely gcc 13.
Bug: https://bugs.gentoo.org/889400
=> acx: Add missing <cstdint> include

configure.ac, lttoolbox/input_file.cc, lttoolbox/input_file.h
To call FstProcessor::generation without creating files or using I/O, I request that InputFile::open_in_memory be added.
=> Add InputFile::open_in_memory

lttoolbox/lt_paradigm.cc, tests/basictest.py, tests/lt_comp/__init__.py, tests/lt_paradigm/__init__.py
Several failing tests have been silently passing! I haven't had a chance to look at these yet, but it seems like it would just return instead of asserting after compiling the test data (since compiling always returned `None`  and it just stopped there)
=> tests: callProc asserts, doesn't return – don't depend on return value

lttoolbox/fst_processor.cc, lttoolbox/fst_processor.h, lttoolbox/lt_paradigm.cc, lttoolbox/lt_proc.cc, tests/basictest.py, tests/lt_comp/__init__.py, tests/lt_paradigm/__init__.py, tests/lt_proc/__init__.py
--surf-bilingual:
```sh
$ echo '^Unk/unk<foo>$ ^Sted/sted<n><nt>$' | lt-proc -o nob-nno.autobil.bin 
^Unk/@Unk$ ^sted<n><nt>/stad<n><m>$
```
--surf-bilingual-keep:
```sh
$ echo '^Unk/unk<foo>$ ^Sted/sted<n><nt>$' | lt-proc -O nob-nno.autobil.bin
^Unk/Unk/@Unk$ ^Sted/sted<n><nt>/stad<n><m>$
```
=> lt-proc --surface-biltrans-keep # assume surface in input, keep surface in output

lttoolbox/fst_processor.cc, lttoolbox/fst_processor.h, lttoolbox/lt_tmxproc.cc
The current lt-tmxproc requires that input ends in punctuation for there to be a match (so not full sentence match, just ending in punct, but if your segments are Titlecased it'll probably DWYM 95% of the time). But I'd like it to work on smaller fragments:
```sh
$ lt-tmxcomp foo-bar word.tmx word.tmx.bin
foo->bar 13 12
$ echo 'Addy Domarus – who or what is Addy Domarus?'|lt-tmxproc word.tmx.bin # current master
Addy Domarus – who or what is [Addedomarus]?
$ echo 'Addy Domarus – who or what is Addy Domarus?'| lttoolbox/lt-tmxproc word.tmx.bin # this pull request
[Addedomarus] – who or what is [Addedomarus]?
$ cat word.tmx
```
```xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE tmx SYSTEM "tmx14.dtd">
<tmx version="1.4">
<header creationtool="Translate Toolkit - po2tmx" …
```
=> let tmx-proc work on space-separated segments as well as those ending in punct

.gitignore, CMakeLists.txt, lttoolbox/CMakeLists.txt, lttoolbox/fst_processor.cc, lttoolbox/fst_processor.h, lttoolbox/stream_reader.cc, lttoolbox/stream_reader.h
This is relevant to https://github.com/apertium/apertium/issues/213 and probably other things
=> Add shared library for parsing stream format

.gitignore, lttoolbox/CMakeLists.txt, lttoolbox/fst_processor.cc, lttoolbox/fst_processor.h, lttoolbox/lt-merge.1, lttoolbox/lt_merge.cc, lttoolbox/state.h, tests/data/pass-through.lsx, tests/lt_merge/__init__.py, tests/lt_proc/__init__.py, tests/run_tests.py
The reason for this is to be able to use CG (or any tool inside the stream really) to mark which parts of the stream should be shielded from translation, e.g. quotes (but perhaps not all quotes).
The pipeline then becomes something like this:
So `lt-merge` runs after tagger:
```sh
$ echo '^ikke/ikke<adv>$ ^«/«<lquot><MERGE_BEG>$^så/så<adv>$ ^veldig/v<adv>$^»/»<rquot><MERGE_END>$ ^bra/bra<adj>$' | lt-merge
```
```r
^ikke/ikke<adv>$ ^«så veldig»/«så veldig»<MERGED>$ ^bra/bra<adj>$
```
If bidix does `<i><w/><s n="MERGED"/></i>` then this passes through unharmed (similarly generator `<i><w/></i><p><l/><r><s n="MERGED"/></r></p>`), and we get
```r
^ikkje<adv>/ikkje$ ^«så veldig»<MERGED>/«så veldig»$ ^bra<adj>/bra$
```
after generation. Then unmerge
```sh
$ echo '^ikkje<adv>/ikkje$ ^«så …
```
=> New `lt-merge` command to merge LU's from BEG to END tag

lttoolbox/fst_processor.cc, lttoolbox/fst_processor.h, tests/data/big-mono.dix, tests/lt_proc/__init__.py
both in analysis (lt-proc -a, with or without compounding -e) and in "bilingual generation" (lt-proc -g -b).
fixes #194
This has zero diffs on first 100k words of my bokmål news test corpus (where the longest all-caps word is only 9 letters long, so it never really kicks in).  
When I test on some wiki dumps I get good things like 
```diff
--- /tmp/wiki-before	2025-03-10 14:17:00.793497651 +0100
+++ /tmp/wiki-after	2025-03-10 14:17:43.574880695 +0100
@@ -11 +11 @@
-FOR AT BOKSEN PÅ FRAMSIDA SKAL OPPDATERAST MÅ DU LAGRE DENNE SIDAN OG SÅ TRYKKJE PÅ LENKJA «Oppdater hovudsida» I BOKSEN TIL HØGRE PÅ OVERVÅKNINGSLISTEN DIN.
+FOR AT BOKSEN PÅ FRAMSIDA SKAL OPPDATERAST MÅ DU LAGRE DENNE SIDAN OG SÅ TRYKKJE PÅ LENKJA «Oppdater hovudsida» I BOKSEN TIL HØGRE PÅ OVERVAKINGSLISTA DI.
```
=> Fallback to analysing lower-cased version on state explosion

CMakeLists.txt, lttoolbox/transducer.cc, tests/data/more-entry-weights.dix, tests/lt_comp/__init__.py
fixes #44, I think.
@flammie @unhammer is there a better way to accomplish this?
=> treat weighted epsilons as non-epsilons
